import numpy as np
import random
import torch

# 1. Define the worker initialization function
def seed_worker(worker_id):
    """
    This runs once inside each worker process when it spawns.
    It takes the unique seed generated by PyTorch's master process 
    and applies it to NumPy and Python's built-in random module.
    """
    # Unique and deterministic seed for each worker
    worker_seed = torch.initial_seed() % 2**32
    
    # Set the seed for NumPy
    np.random.seed(worker_seed)
    
    # Set the seed for Python's random library
    random.seed(worker_seed)